In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv("C:/Users/anany/Downloads/zoo_data.csv")
df

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0              1     0         0     1     0         0        1         1   
1              1     0         0     1     0         0        0         1   
2              0     0         1     0     0         1        1         1   
3              1     0         0     1     0         0        1         1   
4              1     0         0     1     0         0        1         1   
..           ...   ...       ...   ...   ...       ...      ...       ...   
96             1     0         0     1     0         0        0         1   
97             1     0         1     0     1         0        0         0   
98             1     0         0     1     0         0        1         1   
99             0     0         1     0     0         0        0         0   
100            0     1         1     0     1         0        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         0         0     4     0     0         1   
1          1         1         0         0     4     1     0         1   
2          1         0         0         1     0     1     0         0   
3          1         1         0         0     4     0     0         1   
4          1         1         0         0     4     1     0         1   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         0         0     2     1     0         1   
97         0         1         1         0     6     0     0         0   
98         1         1         0         0     4     1     0         1   
99         0         1         0         0     0     0     0         0   
100        1         1         0         0     2     1     0         0   

     class_type  
0             1  
1             1  
2             4  
3             1  
4             1  
..          ...  
96            1  
97            6  
98            1  
99            7  
100           2  

[101 rows x 17 columns]

In [24]:
y=df["class_type"]

In [25]:
df=df.drop("animal name",axis=1)
df=df.drop("class_type",axis=1)

In [26]:
df

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       0         0     1     0         0        1         1        1   
1       0         0     1     0         0        0         1        1   
2       0         1     0     0         1        1         1        1   
3       0         0     1     0         0        1         1        1   
4       0         0     1     0         0        1         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      0         0     1     0         0        0         1        1   
97      0         1     0     1         0        0         0        0   
98      0         0     1     0         0        1         1        1   
99      0         1     0     0         0        0         0        0   
100     1         1     0     1         0        0         0        1   

     backbone  breathes  venomous  fins  legs  tail  domestic  
0           1         0         0     4     0     0         1  
1           1         0         0     4     1     0         1  
2           0         0         1     0     1     0         0  
3           1         0         0     4     0     0         1  
4           1         0         0     4     1     0         1  
..        ...       ...       ...   ...   ...   ...       ...  
96          1         0         0     2     1     0         1  
97          1         1         0     6     0     0         0  
98          1         0         0     4     1     0         1  
99          1         0         0     0     0     0         0  
100         1         0         0     2     1     0         0  

[101 rows x 15 columns]

In [27]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(df,y)

In [28]:
ytrain

10     1
54     1
34     4
100    2
22     1
      ..
23     2
85     7
94     1
47     1
98     1
Name: class_type, Length: 75, dtype: int64

In [29]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [30]:
ypred=classifier.predict(xtest)
ypred

array([2, 1, 3, 6, 6, 1, 1, 4, 2, 1, 1, 1, 2, 2, 1, 4, 2, 2, 7, 1, 6, 1,
       7, 1, 6, 2], dtype=int64)

In [31]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [32]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         7
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         2
           6       0.75      1.00      0.86         3
           7       1.00      0.67      0.80         3

    accuracy                           0.96        26
   macro avg       0.96      0.94      0.94        26
weighted avg       0.97      0.96      0.96        26



In [33]:
print(confusion_matrix(ytest,ypred))

[[10  0  0  0  0  0]
 [ 0  7  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  1  2]]


In [34]:
print(accuracy_score(ytest,ypred))

0.9615384615384616
